# First we got to do some imports (I'm just grabbing the ones from 02 for now)
from pathlib import Path
import platform
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import statsmodels.api as sm
import statsmodels.formula.api as smf

def synthetic_trade_generator(target_variable: str, df: pd.DataFrame, min_value:float = 0.0, printing_state:bool = True) -> pd.DataFrame:
    '''
    Function for creating a synthetic trade column, using gdp and weighted distance parameters.

    input:
        target_variable = string for the column string name which we are working from
        df = pandas DataFrame on which we are doing the work
        min_value = float for minimum value that gets overwritten with a synthetic value

    output:
        df_synthetic = pandas DataFrame with updated columns for missing trade, and new columns for synthetic flags. 
    '''
    df_work = df.copy()

    required_cols = ["gdp_o", "gdp_d", "distw_arithmetic", "contig", "comlang_off", "comlang_ethno", target_variable]

    df_work = df_work[required_cols].dropna()
    df_work = df_work[
        (df_work["gdp_o"] > 0) &
        (df_work["gdp_d"] > 0) &
        (df_work["distw_arithmetic"] > 0) &
        (df_work[f"{target_variable}"] >= 0)
    ]

    df_work["ln_gdp_o"] = np.log(df_work["gdp_o"])
    df_work["ln_gdp_d"] = np.log(df_work["gdp_d"])
    df_work["ln_distw_arithmetic"] = np.log(df_work["distw_arithmetic"])


    X = sm.add_constant(df_work[["ln_gdp_o", "ln_gdp_d", "ln_distw_arithmetic", "contig", "comlang_off", "comlang_ethno"]])
    y = df_work[f"{target_variable}"]

    # Sanity check just in case
    assert np.isfinite(X.values).all()
    assert np.isfinite(y.values).all()

    ppml = sm.GLM(
        y,
        X,
        family=sm.families.Poisson()
    )
    ppml_results = ppml.fit(cov_type="HC1")
    
    # Done training the model on the data we have!
    # Now to create the synthetic data from the ppml
    # This is done by sampling with some variance. 

    # First we find the target values that are missing.

    df_work = df.copy()
    missing_mask = (
        (df_work[f"{target_variable}"].isna() | (df_work[target_variable] < min_value)) &
        (df_work["gdp_o"] > 0) &
        (df_work["gdp_d"] > 0) &
        (df_work["distw_arithmetic"] > 0)
    )

    df_work_missing = df_work.loc[missing_mask].copy()

    df_work_missing["ln_gdp_o"] = np.log(df_work_missing["gdp_o"])
    df_work_missing["ln_gdp_d"] = np.log(df_work_missing["gdp_d"])
    df_work_missing["ln_distw_arithmetic"] = np.log(df_work_missing["distw_arithmetic"])

    X_missing = sm.add_constant(
        df_work_missing[["ln_gdp_o", "ln_gdp_d", "ln_distw_arithmetic", "contig", "comlang_off", "comlang_ethno"]]
    )

    assert np.isfinite(X_missing.values).all()


    # After this we can predict mu-hat --->> This is the conditional mean trade flow (so based on these variables, the expected trade) 
    mu_hat = ppml_results.predict(X_missing)


    # Now we can generate the synthetic trade flows:
    synthetic_trade = np.random.poisson(mu_hat)
    # PPML assumes Poisson conditional mean
    # This preserves zero probability
    # This preserves scale heteroskedasticity
    if printing_state:
        print(f"Amount of rows updated for {target_variable} and threshold {min_value}: {missing_mask.sum()}")


    df_synthetic = df.copy()
    #df_synthetic[f"{target_variable}_synthetic_flag"] = 0

    df_synthetic.loc[missing_mask, f"{target_variable}"] = synthetic_trade
    df_synthetic.loc[missing_mask, f"{target_variable}_synthetic_flag"] = 1
    df_synthetic.loc[~missing_mask, f"{target_variable}_synthetic_flag"] = 0

    return df_synthetic

def synthetic_data_info(list_of_columns:list, df: pd.DataFrame):
    '''
    Function for seeing various information about the changed columns.

    input:
        list_of_columns = A list of strings for column names that have been changed
        df = pandas dataframe with synthetic data generated by the synthetic_trade_generator
    output:

    '''

    descr = []

    for i in list_of_columns:
        syn_flag = f"{i}_synthetic_flag"


        temp_desc = (df.groupby(syn_flag)[i].describe().assign(variable=i))

        descr.append(temp_desc)

    resulting_descr = pd.concat(descr)

    for i in list_of_columns:
        plt.hist(
            df.loc[df[f"{i}_synthetic_flag"] == 0, i],
            bins=50, alpha=0.6, label="Observed"
        )
        plt.hist(
            df.loc[df[f"{i}_synthetic_flag"] == 1, i],
            bins=50, alpha=0.6, label="Synthetic"
        )
        plt.legend()
        plt.title(i)
        plt.show()

    
    return resulting_descr

def main(set_random_state:int = 42, printing_state:bool = True):
    '''
    Calling all functions for synthetic datasets to update the 3 initial dataframes.
    '''
    # Random seed for reproducibility
    np.random.seed(set_random_state)
    Path("data/synth").mkdir(parents=True, exist_ok=True)

    # For all 3 lag times...
    df_zero = pd.read_csv("data/ecowas_df_full_lag_zero.csv")
    df_one = pd.read_csv("data/ecowas_df_full_lag_one.csv")
    df_two = pd.read_csv("data/ecowas_df_full_lag_two.csv")

    df_list = [df_zero, df_one, df_two]
    names = ["zero", "one", "two"]
    threshold = [0, 10, 100]


    columns_to_update = ['tradeflow_baci', 'tradeflow_comtrade_o', 'tradeflow_comtrade_d', 'tradeflow_imf_o', 'tradeflow_imf_d']

    for thresh in threshold:
        for name, df in zip(names, df_list):
            df_update = df.copy()

            if printing_state:
                print(f"We are in the dataframe {name}")

            for col in columns_to_update:
                df_update = synthetic_trade_generator(col, df_update, thresh, printing_state)

            #statistics_synth = synthetic_data_info(columns_to_update, df_update)
            #print(statistics_synth)

            # Before we save to csv, we need to update the combined_trade column, as tradeflow_baci only deals in exports
            # Then we can aggregate total trade per dyad for each year
            df_update = df_update.drop(columns=["combined_trade_baci"], errors="ignore")
            combined = (
                df_update.groupby(["dyad", "year"])["tradeflow_baci"]
                .sum()
                .reset_index()
                .rename(columns={"tradeflow_baci": "combined_trade_baci"})
            )

            # And we tack this onto the end of our dataframe. Our new column "combined_trade" can now be used
            df_update = df_update.merge(combined, on=["dyad", "year"], how="left")

            df_update.to_csv(f"data/synth/ecowas_df_synthetic_full_lag_{name}_{thresh}.csv", index=False)

if __name__ == "__main__":
    main()